import json
import os
import shutil
from datetime import datetime

dir_path = os.path.dirname(os.path.realpath(__file__))
allowed_extension = [".txt", ".json", ".properties"]
file_present = []
date_add = datetime.now()
folder_name = "report" + date_add.strftime("-%d-%m-%Y-%H-%M-%S")
report_folder = dir_path + "/allure"

count = 0

'''Don't delete report_preference folder'''


# Search function search for files in the allure directory and if files found it append to the list named file_present
def search():
    global count
    for ext in os.listdir(report_folder):
        if os.path.isfile(report_folder + "/" + ext):
            file_present.append(ext)


# report_arrange function moves the file generated by allure report to another folder also added with report_preferences
def report_arrange():
    if len(file_present) >= 2:
        os.mkdir(f'{report_folder}/{folder_name}')
        for i in file_present:
            shutil.move(f'{report_folder}/{i}', f'{report_folder}/{folder_name}/')

        shutil.copy(f'{report_folder}/report_preference/categories.json', f'{report_folder}/{folder_name}/')
        shutil.copy(f'{report_folder}/report_preference/environment.properties', f'{report_folder}/{folder_name}/')
        print(f"report directory generated ")


def show_report():
    search()
    report_arrange()
    file_present.clear()
    folder_list = []
    for ext in os.listdir(report_folder):

        if not os.path.isfile((report_folder + "/" + ext)):
            if ext == ".pytest_cache" or ext == "report_preference":
                pass
            else:
                folder_list.append(ext)

    cmd = os.popen(f"allure serve allure/{folder_list[len(folder_list) - 1]}/")
    print(cmd.read())
    folder_list.clear()


show_report()
